 List<Map<String, dynamic>> addresses = [
    {
      'idVal': 1,
      'pays': 'niger',
      'ville': 'niamey',
      'quartier': 'bobiel',
      'rue': 'rue 25',
    },
    {
      'idVal': 2,
      'pays': 'niger',
      'ville': 'niamey',
      'quartier': 'yantala',
      'rue': 'rue 45',
    },
    {
      'idVal': 3,
      'pays': 'niger',
      'ville': 'niamey',
      'quartier': 'lazaret',
      'rue': 'rue 12',
    },
    {
      'idVal': 4,
      'pays': 'niger',
      'ville': 'niamey',
      'quartier': 'harobanda',
      'rue': 'rue 18',
    },
    {
      'idVal': 5,
      'pays': 'niger',
      'ville': 'niamey',
      'quartier': 'wadata',
      'rue': 'rue 32',
    },
    {
      'idVal': 6,
      'pays': 'niger',
      'ville': 'niamey',
      'quartier': 'talladje',
      'rue': 'rue 21',
    },
    {
      'idVal': 7,
      'pays': 'niger',
      'ville': 'niamey',
      'quartier': 'plateau',
      'rue': 'avenue de la mairie',
    },
    {
      'idVal': 8,
      'pays': 'niger',
      'ville': 'niamey',
      'quartier': 'koira kano',
      'rue': 'rue KK 15',
    },
    {
      'idVal': 9,
      'pays': 'niger',
      'ville': 'maradi',
      'quartier': 'ali dan sofo',
      'rue': 'rue 10',
    },
    {
      'idVal': 10,
      'pays': 'niger',
      'ville': 'maradi',
      'quartier': 'zaria',
      'rue': 'rue 08',
    },
    {
      'idVal': 11,
      'pays': 'niger',
      'ville': 'zinder',
      'quartier': 'birni',
      'rue': 'rue 15',
    },
    {
      'idVal': 12,
      'pays': 'niger',
      'ville': 'zinder',
      'quartier': 'kara kara',
      'rue': 'rue 22',
    },
    {
      'idVal': 13,
      'pays': 'niger',
      'ville': 'tahoua',
      'quartier': 'sabongari',
      'rue': 'rue 05',
    },
    {
      'idVal': 14,
      'pays': 'niger',
      'ville': 'tahoua',
      'quartier': 'toudou',
      'rue': 'rue 14',
    },
    {
      'idVal': 15,
      'pays': 'niger',
      'ville': 'dosso',
      'quartier': 'tondibia',
      'rue': 'rue 07',
    },
    {
      'idVal': 16,
      'pays': 'niger',
      'ville': 'agadez',
      'quartier': 'dagamanet',
      'rue': 'rue principale',
    },
    {
      'idVal': 17,
      'pays': 'niger',
      'ville': 'diffa',
      'quartier': 'centre ville',
      'rue': 'rue 03',
    },
    {
      'idVal': 18,
      'pays': 'niger',
      'ville': 'tillaberi',
      'quartier': 'centre ville',
      'rue': 'rue 06',
    },
    {
      'idVal': 19,
      'pays': 'niger',
      'ville': 'gaya',
      'quartier': 'centre ville',
      'rue': 'rue 11',
    },
    {
      'idVal': 20,
      'pays': 'niger',
      'ville': 'birni n konni',
      'quartier': 'centre ville',
      'rue': 'rue 09',
    },
  ];
