 List<Map<String, dynamic>> addresses = [
    {
      'idVal': 1,
      'pays': 'niger',
      'ville': 'niamey',
      'quartier': 'bobiel',
    },
    {
      'idVal': 2,
      'pays': 'niger',
      'ville': 'niamey',
      'quartier': 'yantala',
    },
    {
      'idVal': 3,
      'pays': 'niger',
      'ville': 'niamey',
      'quartier': 'lazaret',
    },
    {
      'idVal': 4,
      'pays': 'niger',
      'ville': 'niamey',
      'quartier': 'harobanda',
    },
    {
      'idVal': 5,
      'pays': 'niger',
      'ville': 'niamey',
      'quartier': 'wadata',
    },
    {
      'idVal': 6,
      'pays': 'niger',
      'ville': 'niamey',
      'quartier': 'talladje',
    },
    {
      'idVal': 7,
      'pays': 'niger',
      'ville': 'niamey',
      'quartier': 'plateau',
    },
    {
      'idVal': 8,
      'pays': 'niger',
      'ville': 'niamey',
      'quartier': 'koira kano',
    },
    {
      'idVal': 9,
      'pays': 'niger',
      'ville': 'maradi',
      'quartier': 'ali dan sofo',
    },
    {
      'idVal': 10,
      'pays': 'niger',
      'ville': 'maradi',
      'quartier': 'zaria',
    },
    {
      'idVal': 11,
      'pays': 'niger',
      'ville': 'zinder',
      'quartier': 'birni',
    },
    {
      'idVal': 12,
      'pays': 'niger',
      'ville': 'zinder',
      'quartier': 'kara kara',
    },
    {
      'idVal': 13,
      'pays': 'niger',
      'ville': 'tahoua',
      'quartier': 'sabongari',
    },
    {
      'idVal': 14,
      'pays': 'niger',
      'ville': 'tahoua',
      'quartier': 'toudou',
    },
    {
      'idVal': 15,
      'pays': 'niger',
      'ville': 'dosso',
      'quartier': 'tondibia',
    },
    {
      'idVal': 16,
      'pays': 'niger',
      'ville': 'agadez',
      'quartier': 'dagamanet',
    },
    {
      'idVal': 17,
      'pays': 'niger',
      'ville': 'diffa',
      'quartier': 'centre ville',
    },
    {
      'idVal': 18,
      'pays': 'niger',
      'ville': 'tillaberi',
      'quartier': 'centre ville',
    },
    {
      'idVal': 19,
      'pays': 'niger',
      'ville': 'gaya',
      'quartier': 'centre ville',
    },
    {
      'idVal': 20,
      'pays': 'niger',
      'ville': 'birni n konni',
      'quartier': 'centre ville',
    },
  ];
