
  List<Map<String, dynamic>> horaires = [
    {
      'idVal': 1,
      'joursOuverts': ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi'],
      'heureOuverture': DateTime(2026, 1, 1, 8, 0),
      'heureFermeture': DateTime(2026, 1, 1, 18, 0),
      'demiJour': 'vendredi',
      'weekend': 'samedi-dimanche',
      'heureFermetureDemijournee': DateTime(2026, 1, 1, 12, 0),
    },
    {
      'idVal': 2,
      'joursOuverts': 'lmmjvs',
      'heureOuverture': DateTime(2026, 1, 1, 8, 0),
      'heureFermeture': DateTime(2026, 1, 1, 18, 0),
      'demiJour': 'samedi',
      'weekend': 'dimanche',
      'heureFermetureDemijournee': DateTime(2026, 1, 1, 12, 0),
    },
    {
      'idVal': 3,
      'joursOuverts': 'lmmjvsd',
      'heureOuverture': DateTime(2026, 1, 1, 7, 0),
      'heureFermeture': DateTime(2026, 1, 1, 22, 0),
      'demiJour': '',
      'weekend': '',
      'heureFermetureDemijournee': DateTime(2026, 1, 1, 22, 0),
    },
    {
      'idVal': 4,
      'joursOuverts': 'lmmjv',
      'heureOuverture': DateTime(2026, 1, 1, 8, 0),
      'heureFermeture': DateTime(2026, 1, 1, 17, 0),
      'demiJour': 'vendredi',
      'weekend': 'samedi-dimanche',
      'heureFermetureDemijournee': DateTime(2026, 1, 1, 13, 0),
    },
    {
      'idVal': 5,
      'joursOuverts': 'lmmjvs',
      'heureOuverture': DateTime(2026, 1, 1, 9, 0),
      'heureFermeture': DateTime(2026, 1, 1, 19, 0),
      'demiJour': 'samedi',
      'weekend': 'dimanche',
      'heureFermetureDemijournee': DateTime(2026, 1, 1, 14, 0),
    },
    {
      'idVal': 6,
      'joursOuverts': 'lmmjv',
      'heureOuverture': DateTime(2026, 1, 1, 8, 0),
      'heureFermeture': DateTime(2026, 1, 1, 16, 0),
      'demiJour': 'vendredi',
      'weekend': 'samedi-dimanche',
      'heureFermetureDemijournee': DateTime(2026, 1, 1, 12, 30),
    },
    {
      'idVal': 7,
      'joursOuverts': 'lmmjvs',
      'heureOuverture': DateTime(2026, 1, 1, 8, 30),
      'heureFermeture': DateTime(2026, 1, 1, 20, 0),
      'demiJour': 'dimanche',
      'weekend': 'dimanche après-midi',
      'heureFermetureDemijournee': DateTime(2026, 1, 1, 13, 0),
    },
    {
      'idVal': 8,
      'joursOuverts': 'lmmjv',
      'heureOuverture': DateTime(2026, 1, 1, 7, 30),
      'heureFermeture': DateTime(2026, 1, 1, 16, 30),
      'demiJour': 'mercredi',
      'weekend': 'samedi-dimanche',
      'heureFermetureDemijournee': DateTime(2026, 1, 1, 12, 0),
    },
    {
      'idVal': 9,
      'joursOuverts': 'lmmjv',
      'heureOuverture': DateTime(2026, 1, 1, 8, 0),
      'heureFermeture': DateTime(2026, 1, 1, 15, 30),
      'demiJour': 'vendredi',
      'weekend': 'samedi-dimanche',
      'heureFermetureDemijournee': DateTime(2026, 1, 1, 12, 30),
    },
    {
      'idVal': 10,
      'joursOuverts': 'lmmjvsd',
      'heureOuverture': DateTime(2026, 1, 1, 8, 0),
      'heureFermeture': DateTime(2026, 1, 1, 23, 0),
      'demiJour': '',
      'weekend': '',
      'heureFermetureDemijournee': DateTime(2026, 1, 1, 23, 0),
    },
  ];
