List<Map<String, dynamic>> services = [
  {
    'idVal': 1,
    'categorieVal': 'Sante',
    'sousCategorieVal': 'Pharmacie',
    'gestionnaireIdVal': 0,
    'horaire': '8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-12:00 close',
    'nomserviceVal': 'Pharmacie KK',
    'aproposVal':
        'Pharmacie proposant des médicaments, produits de santé et conseils pharmaceutiques aux habitants.',
    'addressIdVal': 1,
    'telephoneVal': '96 40 49 35',
    'coordonneeIdVal': 1,
    'gardeVal': true,
    'statutActuelVal': 'ouvert',
    'urlImageVal': '',
  },
  {
    'idVal': 2,
    'categorieVal': 'Sante',
    'sousCategorieVal': 'Sante',
    'gestionnaireIdVal': 3,
    'horaire': '',
    'nomserviceVal': 'Centre de Santé Bobiel',
    'aproposVal':
        'Centre de santé proposant des services de consultation, de soins et d’orientation médicale.',
    'addressIdVal': 2,
    'telephoneVal': '90 12 34 56',
    'coordonneeIdVal': 2,
    'gardeVal': false,
    'statutActuelVal': 'ouvert',
    'urlImageVal': '',
  },
  {
    'idVal': 3,
    'categorieVal': 'Education',
    'sousCategorieVal': 'Ecole',
    'gestionnaireIdVal': 4,
    'horaire': '8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-12:00 close',
    'nomserviceVal': 'Ecole Primaire Yantala',
    'aproposVal':
        'Établissement scolaire destiné à l’enseignement primaire et à l’accompagnement éducatif des élèves.',
    'addressIdVal': 3,
    'telephoneVal': '91 23 45 67',
    'coordonneeIdVal': 3,
    'gardeVal': false,
    'statutActuelVal': 'ferme',
    'urlImageVal': '',
  },
  {
    'idVal': 4,
    'categorieVal': 'Education',
    'sousCategorieVal': 'Universite',
    'gestionnaireIdVal': 7,
    'horaire': '8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-12:00 close',
    'nomserviceVal': 'Universite de Niamey',
    'aproposVal':
        'Établissement universitaire proposant des formations supérieures dans plusieurs domaines d’études.',
    'addressIdVal': 4,
    'telephoneVal': '92 34 56 78',
    'coordonneeIdVal': 4,
    'gardeVal': false,
    'statutActuelVal': 'ouvert',
    'urlImageVal': '',
  },
  {
    'idVal': 5,
    'categorieVal': 'Securite',
    'sousCategorieVal': 'Gendarmerie',
    'gestionnaireIdVal': 2,
    'horaire': '',
    'nomserviceVal': 'Gendarmerie Nationale',
    'aproposVal':
        'Service chargé notamment de la sécurité des personnes et des biens ainsi que du maintien de l’ordre.',
    'addressIdVal': 5,
    'telephoneVal': '93 45 67 89',
    'coordonneeIdVal': 5,
    'gardeVal': true,
    'statutActuelVal': 'ouvert',
    'urlImageVal': '',
  },
  {
    'idVal': 6,
    'categorieVal': 'Securite',
    'sousCategorieVal': 'Commissariat',
    'gestionnaireIdVal': 2,
    'horaire': '',
    'nomserviceVal': 'Commissariat Central',
    'aproposVal':
        'Service de police destiné à accueillir les citoyens et à assurer différentes missions de sécurité publique.',
    'addressIdVal': 6,
    'telephoneVal': '94 56 78 90',
    'coordonneeIdVal': 6,
    'gardeVal': true,
    'statutActuelVal': 'ouvert',
    'urlImageVal': '',
  },
  {
    'idVal': 7,
    'categorieVal': 'Services Publics',
    'sousCategorieVal': 'Mairie',
    'gestionnaireIdVal': 7,
    'horaire': '8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-12:00 close',
    'nomserviceVal': 'Mairie Centrale de Niamey',
    'aproposVal':
        'Administration municipale proposant différents services et démarches aux habitants de la commune.',
    'addressIdVal': 7,
    'telephoneVal': '95 67 89 01',
    'coordonneeIdVal': 7,
    'gardeVal': false,
    'statutActuelVal': 'ouvert',
    'urlImageVal': '',
  },
  {
    'idVal': 8,
    'categorieVal': 'Finance',
    'sousCategorieVal': 'Banque',
    'gestionnaireIdVal': 2,
    'horaire': '8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-12:00 close',
    'nomserviceVal': 'Banque Nationale',
    'aproposVal':
        'Établissement financier proposant des services bancaires aux particuliers et aux professionnels.',
    'addressIdVal': 8,
    'telephoneVal': '96 78 90 12',
    'coordonneeIdVal': 8,
    'gardeVal': false,
    'statutActuelVal': 'ferme',
    'urlImageVal': '',
  },
  {
    'idVal': 9,
    'categorieVal': 'Logement',
    'sousCategorieVal': 'Hotel',
    'gestionnaireIdVal': 8,
    'horaire': '',
    'nomserviceVal': 'Hotel Sahel',
    'aproposVal':
        'Hôtel proposant des chambres et des services d’accueil pour les voyageurs et visiteurs.',
    'addressIdVal': 9,
    'telephoneVal': '97 89 01 23',
    'coordonneeIdVal': 9,
    'gardeVal': true,
    'statutActuelVal': 'ouvert',
    'urlImageVal': '',
  },
  {
    'idVal': 10,
    'categorieVal': 'Restauration',
    'sousCategorieVal': 'Restaurant',
    'gestionnaireIdVal': 10,
    'horaire': '8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 ',
    'nomserviceVal': 'Restaurant La Palmeraie',
    'aproposVal':
        'Restaurant proposant différents plats et boissons dans un cadre adapté aux repas en famille ou entre amis.',
    'addressIdVal': 10,
    'telephoneVal': '98 01 23 45',
    'coordonneeIdVal': 10,
    'gardeVal': false,
    'statutActuelVal': 'ouvert',
    'urlImageVal': '',
  },
  {
    'idVal': 11,
    'categorieVal': 'Commercial',
    'sousCategorieVal': 'Commercial',
    'gestionnaireIdVal': 4,
    'horaire': '8:30-19:00 8:30-19:00 8:30-19:00 8:30-19:00 8:30-19:00 8:30-19:00 8:30-19:00',
    'nomserviceVal': 'Grand Marche de Zinder',
    'aproposVal':
        'Espace commercial regroupant de nombreux vendeurs et proposant différents produits aux habitants et visiteurs.',
    'addressIdVal': 11,
    'telephoneVal': '99 12 34 56',
    'coordonneeIdVal': 11,
    'gardeVal': false,
    'statutActuelVal': 'ouvert',
    'urlImageVal': '',
  },
  {
    'idVal': 12,
    'categorieVal': 'Securite',
    'sousCategorieVal': 'Sapeurs Pompiers',
    'gestionnaireIdVal': 2,
    'horaire': '',
    'nomserviceVal': 'Caserne des Sapeurs-Pompiers',
    'aproposVal':
        'Service d’intervention d’urgence spécialisé notamment dans la lutte contre les incendies et le secours aux personnes.',
    'addressIdVal': 12,
    'telephoneVal': '90 23 45 67',
    'coordonneeIdVal': 12,
    'gardeVal': true,
    'statutActuelVal': 'ouvert',
    'urlImageVal': '',
  },
  {
    'idVal': 13,
    'categorieVal': 'Services Publics',
    'sousCategorieVal': 'Impot',
    'gestionnaireIdVal': 7,
    'horaire': '8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-12:00 close',
    'nomserviceVal': 'Centre des Impots',
    'aproposVal':
        'Service administratif chargé de l’accueil des contribuables et de différentes démarches fiscales.',
    'addressIdVal': 13,
    'telephoneVal': '91 34 56 78',
    'coordonneeIdVal': 13,
    'gardeVal': false,
    'statutActuelVal': 'ferme',
    'urlImageVal': '',
  },
  {
    'idVal': 14,
    'categorieVal': 'Services Publics',
    'sousCategorieVal': 'Justice',
    'gestionnaireIdVal': 7,
    'horaire': '8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-12:00 close',
    'nomserviceVal': 'Tribunal de Tahoua',
    'aproposVal':
        'Institution judiciaire où sont traitées différentes affaires relevant de la compétence du tribunal.',
    'addressIdVal': 14,
    'telephoneVal': '92 45 67 89',
    'coordonneeIdVal': 14,
    'gardeVal': false,
    'statutActuelVal': 'ouvert',
    'urlImageVal': '',
  },
  {
    'idVal': 15,
    'categorieVal': 'Humanitaire',
    'sousCategorieVal': 'Orphelinat',
    'gestionnaireIdVal': 9,
    'horaire': '',
    'nomserviceVal': 'Orphelinat La Joie',
    'aproposVal':
        'Structure d’accueil et d’accompagnement destinée à apporter un cadre de vie et un soutien aux enfants vulnérables.',
    'addressIdVal': 15,
    'telephoneVal': '93 56 78 90',
    'coordonneeIdVal': 15,
    'gardeVal': false,
    'statutActuelVal': 'ouvert',
    'urlImageVal': '',
  },
  {
    'idVal': 16,
    'categorieVal': 'Culte et Religion',
    'sousCategorieVal': 'Mosquee',
    'gestionnaireIdVal': 10,
    'horaire': '',
    'nomserviceVal': 'Grande Mosquee dAgadez',
    'aproposVal':
        'Lieu de culte destiné à la prière et aux activités religieuses de la communauté musulmane.',
    'addressIdVal': 16,
    'telephoneVal': '94 67 89 01',
    'coordonneeIdVal': 16,
    'gardeVal': false,
    'statutActuelVal': 'ouvert',
    'urlImageVal': '',
  },
  {
    'idVal': 17,
    'categorieVal': 'Culte et Religion',
    'sousCategorieVal': 'Eglise',
    'gestionnaireIdVal': 9,
    'horaire': '',
    'nomserviceVal': 'Eglise de Diffa',
    'aproposVal':
        'Lieu de culte accueillant les fidèles pour les célébrations et différentes activités religieuses.',
    'addressIdVal': 17,
    'telephoneVal': '95 78 90 12',
    'coordonneeIdVal': 17,
    'gardeVal': false,
    'statutActuelVal': 'ferme',
    'urlImageVal': '',
  },
  {
    'idVal': 18,
    'categorieVal': 'Transport',
    'sousCategorieVal': 'Voyage',
    'gestionnaireIdVal': 4,
    'horaire': '8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 ',
    'nomserviceVal': 'Autogare de Tillaberi',
    'aproposVal':
        'Gare destinée aux voyageurs et aux services de transport reliant différentes localités.',
    'addressIdVal': 18,
    'telephoneVal': '96 89 01 23',
    'coordonneeIdVal': 18,
    'gardeVal': false,
    'statutActuelVal': 'ouvert',
    'urlImageVal': '',
  },
  {
    'idVal': 19,
    'categorieVal': 'Loisirs',
    'sousCategorieVal': 'Espace de loisirs',
    'gestionnaireIdVal': 10,
    'horaire': '',
    'nomserviceVal': 'Espace Public',
    'aproposVal':
        'Espace destiné à la détente, aux rencontres et aux activités de loisirs accessibles au public.',
    'addressIdVal': 19,
    'telephoneVal': '97 90 12 34',
    'coordonneeIdVal': 19,
    'gardeVal': false,
    'statutActuelVal': 'ouvert',
    'urlImageVal': '',
  },
  {
    'idVal': 20,
    'categorieVal': 'Services Publics',
    'sousCategorieVal': 'Ministere',
    'gestionnaireIdVal': 7,
    'horaire': '8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-18:00 8:30-12:00 close',
    'nomserviceVal': 'Ministere des Services Publics',
    'aproposVal':
        'Administration publique fournissant des informations et services liés aux démarches et aux services publics.',
    'addressIdVal': 20,
    'telephoneVal': '98 01 23 45',
    'coordonneeIdVal': 20,
    'gardeVal': false,
    'statutActuelVal': 'ferme',
    'urlImageVal': '',
  },
];