List<Map<String, dynamic>> urgences = [
  {
    'idVal': 1,
    'nomserviceVal': 'Sapeurs-pompiers',
    'telephoneVal': '18',
    'descriptionVal': 'En cas d\'incendie, d\'accident ou de situation nécessitant une intervention rapide, appelez les sapeurs-pompiers.',
    'couleur': 'red',
  },
  {
    'idVal': 2,
    'nomserviceVal': 'Police nationale',
    'telephoneVal': '17',
    'descriptionVal': 'En cas d\'agression, de vol, de cambriolage ou de situation nécessitant l\'intervention de la police.',
    'couleur': 'blue',
  },
  {
    'idVal': 3,
    'nomserviceVal': 'Gendarmerie nationale',
    'telephoneVal': '17',
    'descriptionVal': 'Contactez la gendarmerie pour signaler une situation dangereuse ou nécessitant une intervention.',
    'couleur': 'green',
  },
  {
    'idVal': 4,
    'nomserviceVal': 'Urgence médicale',
    'telephoneVal': '15',
    'descriptionVal': 'Appelez en cas de malaise grave, blessure importante ou situation médicale urgente.',
    'couleur': 'red',
  },
  {
    'idVal': 5,
    'nomserviceVal': 'Ambulance',
    'telephoneVal': '15',
    'descriptionVal': 'Appelez pour demander une assistance médicale urgente ou une évacuation.',
    'couleur': 'red',
  },
  {
    'idVal': 6,
    'nomserviceVal': 'Protection civile',
    'telephoneVal': '18',
    'descriptionVal': 'Contactez les services de protection civile en cas de catastrophe ou d\'accident.',
    'couleur': 'orange',
  },
  {
    'idVal': 7,
    'nomserviceVal': 'Police secours',
    'telephoneVal': '17',
    'descriptionVal': 'Appelez pour signaler rapidement une situation de danger ou un problème de sécurité.',
    'couleur': 'blue',
  },
  {
    'idVal': 8,
    'nomserviceVal': 'Urgence accident',
    'telephoneVal': '18',
    'descriptionVal': 'En cas d\'accident de circulation ou autre accident nécessitant des secours.',
    'couleur': 'orange',
  },
  {
    'idVal': 9,
    'nomserviceVal': 'Assistance citoyenne',
    'telephoneVal': '17',
    'descriptionVal': 'Utilisez ce numéro pour signaler une situation de danger nécessitant une intervention.',
    'couleur': 'blue',
  },
  {
    'idVal': 10,
    'nomserviceVal': 'Secours général',
    'telephoneVal': '18',
    'descriptionVal': 'Appelez en cas de situation grave nécessitant rapidement l\'intervention des services de secours.',
    'couleur': 'red',
  },
];
