  List<Map<String, dynamic>> users = [
    {
      'idVal': 1,
      'roleVal': 'superAdmin',
      'nomVal': 'Omar',
      'prenomVal': 'Epiphane',
      'emailVal': 'omar@gmail.com',
      'telephoneVal': '0022796008844',
      'villeVal': 'Niamey',
      'quartierVal': 'Bobiel',
      'proffessionVal': 'Developpeur',
      'passwordVal': '1234.1',
    },
    {
      'idVal': 2,
      'roleVal': 'admin',
      'nomVal': 'Ibrahim',
      'prenomVal': 'Issa',
      'emailVal': 'issa@gmail.com',
      'telephoneVal': '',
      'villeVal': 'Niamey',
      'quartierVal': 'Recasement',
      'proffessionVal': 'RH-Mairie',
      'passwordVal': '',
    },
    {
      'idVal': 3,
      'roleVal': 'citoyen',
      'nomVal': 'Aboubacar',
      'prenomVal': 'Ango',
      'emailVal': 'ango@gmail.com',
      'telephoneVal': '0022796954834',
      'villeVal': 'Niamey',
      'quartierVal': 'Harobanda',
      'proffessionVal': 'Etudiant',
      'passwordVal': '1234.3',
    },
    {
      'idVal': 4,
      'roleVal': 'citoyen',
      'nomVal': 'Moussa',
      'prenomVal': 'Adamou',
      'emailVal': 'moussa@gmail.com',
      'telephoneVal': '0022797001122',
      'villeVal': 'Niamey',
      'quartierVal': 'Yantala',
      'proffessionVal': 'Commercant',
      'passwordVal': '1234.4',
    },
    {
      'idVal': 5,
      'roleVal': 'citoyen',
      'nomVal': 'Amina',
      'prenomVal': 'Mahamadou',
      'emailVal': 'amina@gmail.com',
      'telephoneVal': '0022797112233',
      'villeVal': 'Niamey',
      'quartierVal': 'Lazaret',
      'proffessionVal': 'Enseignante',
      'passwordVal': '1234.5',
    },
    {
      'idVal': 6,
      'roleVal': 'citoyen',
      'nomVal': 'Youssouf',
      'prenomVal': 'Ousmane',
      'emailVal': 'youssouf@gmail.com',
      'telephoneVal': '0022797223344',
      'villeVal': 'Niamey',
      'quartierVal': 'Kirkissoye',
      'proffessionVal': 'Chauffeur',
      'passwordVal': '1234.6',
    },
    {
      'idVal': 7,
      'roleVal': 'admin',
      'nomVal': 'Fatima',
      'prenomVal': 'Issoufou',
      'emailVal': 'fatima@gmail.com',
      'telephoneVal': '0022797334455',
      'villeVal': 'Niamey',
      'quartierVal': 'Plateau',
      'proffessionVal': 'Agent administratif',
      'passwordVal': '1234.7',
    },
    {
      'idVal': 8,
      'roleVal': 'citoyen',
      'nomVal': 'Mahamadou',
      'prenomVal': 'Sani',
      'emailVal': 'mahamadou@gmail.com',
      'telephoneVal': '0022797445566',
      'villeVal': 'Niamey',
      'quartierVal': 'Talladje',
      'proffessionVal': 'Electricien',
      'passwordVal': '1234.8',
    },
    {
      'idVal': 9,
      'roleVal': 'citoyen',
      'nomVal': 'Halima',
      'prenomVal': 'Abdoul',
      'emailVal': 'halima@gmail.com',
      'telephoneVal': '0022797556677',
      'villeVal': 'Niamey',
      'quartierVal': 'Wadata',
      'proffessionVal': 'Infirmiere',
      'passwordVal': '1234.9',
    },
    {
      'idVal': 10,
      'roleVal': 'citoyen',
      'nomVal': 'Amadou',
      'prenomVal': 'Moussa',
      'emailVal': 'amadou@gmail.com',
      'telephoneVal': '0022797667788',
      'villeVal': 'Niamey',
      'quartierVal': 'Koira Kano',
      'proffessionVal': 'Entrepreneur',
      'passwordVal': '1234.10',
    },
  ];
